baseURL = "https://ranya.run"
languageCode = "en"
defaultContentLanguage = "en"
title = "Ran's Blog"
theme = "typographical"

enableRobotsTXT = true

[taxonomies]
	tag = "tags"
	category = "category"
	series = "series"

[params.dropCap]
  enable = true
  
summaryLength = 50

accentColour = "#FF6B6B"

[permalinks]
  post = "/:title/"
  page = "/:title/"

favicon = "/images/favicon.ico"

[author]
    name = "Nasu Rei"

[params]
    [params.copyright]
        icon = "<i class="far fa-copyright"></i>"
        message = "Glue Drinkers' Association, some rights reserved :D"
  
# Navigation
[menu]
[[menu.main]]
identifier = "categories"
pre = "<i class='fa-solid fa-filter'></i>"
title = "Categories"
url = "/category"
weight = 2

[[menu.main]]
identifier = "tags"
pre = "<i class='fa-solid fa-tags'></i>"
title = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
identifier = "archive"
pre = "<i class='fas fa-archive'></i>"
title = "Archive"
url = "/archive/"
weight = 1

[[menu.main]]
identifier = "about"
pre = "<i class='fas fa-info'></i>"
title = "About"
url = "/about/"
weight = 2
